id: A52882A5B
base_file: f5D32.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:39:36.313969
  last_modified_at: 2022-06-11 13:39:36.313975
